server:
  port: 8000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 
    username:
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
project:
  image: images
